
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-2
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2MDUxNjQ2","is_bot":false,"login":"AlejandroRR16","name":""},"headRefName":"Alejandro-toggle-rider-role-backend","number":47,"title":"ARR - added backend code for toggleRider; pass tests and mutation test","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/47"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-pitest-workflows-13-14","number":34,"title":"pc - fix workflows 13 and 14 for pitest","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/34"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-workflow-32","number":33,"title":"pc - update workflow 32 with branch information","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/33"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-Chatroom-backend-post-get","number":30,"title":"Leon chatroom backend post get","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/30"},{"author":{"id":"MDQ6VXNlcjY0ODczNzQ2","is_bot":false,"login":"cherylstanley","name":"Cheryl Stanley"},"headRefName":"PageNotFound-Cheryl","number":27,"title":"Page not found cheryl","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/27"},{"author":{"id":"MDQ6VXNlcjc3NzA5OTIx","is_bot":false,"login":"Simon-Lai103","name":""},"headRefName":"Simon-Cart","number":24,"title":"Simon-Add CRUD & Backend stuff","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/24"},{"author":{"id":"MDQ6VXNlcjg2NzQ0NDUx","is_bot":false,"login":"yqin01","name":"Yicheng Qin"},"headRefName":"tim-add-driverToggleButton","number":23,"title":"Tim add driver toggle button","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/23"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-fix-bug-login-interceptor","number":16,"title":"Leon fix bug login interceptor","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/16"}]
