
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-2
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyOTAxMTI4","is_bot":false,"login":"jtmnguyen","name":""},"headRefName":"jessica-change-navbar-to-ucsb-colors","number":17,"title":"jessica-change navbar to ucsb colors","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/17"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-fix-bug-login-interceptor","number":16,"title":"Leon fix bug login interceptor","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/16"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-Chatroom-backend","number":14,"title":"Leon chatroom backend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/14"},{"author":{"id":"MDQ6VXNlcjcyOTAxMTI4","is_bot":false,"login":"jtmnguyen","name":""},"headRefName":"jessica-add-toggleDriver","number":8,"title":"jn-added backend code for toggleDriver backend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/8"}]
