
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-2
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NzA5OTIx","is_bot":false,"login":"Simon-Lai103","name":""},"headRefName":"Simon-Cart","number":24,"title":"Simon-Add CRUD & Backend stuff","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/24"},{"author":{"id":"MDQ6VXNlcjg2NzQ0NDUx","is_bot":false,"login":"yqin01","name":"Yicheng Qin"},"headRefName":"tim-add-driverToggleButton","number":23,"title":"Tim add driver toggle button","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/23"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-establish-driver-role","number":21,"title":"add driver role at login if driver is true in db","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/21"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-add-cartoon-stork-to-nav","number":20,"title":"Leon add cartoon stork to nav","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/20"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-fix-bug-login-interceptor","number":16,"title":"Leon fix bug login interceptor","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/16"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-Chatroom-backend","number":14,"title":"Leon chatroom backend","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/14"}]
