
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-gauchoride-s23-5pm-2
owner: ucsb-cs156-s23
repo_name: proj-gauchoride-s23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-chatroom-backend-put-delete","number":63,"title":"Leon chatroom backend PUT/DELETE","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/63"},{"author":{"id":"MDQ6VXNlcjU2MDUxNjQ2","is_bot":false,"login":"AlejandroRR16","name":""},"headRefName":"Alejandro-Ride-Controller","number":62,"title":"ARR - Added POST/GET for ride requests","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/62"},{"author":{"id":"MDQ6VXNlcjY0ODczNzQ2","is_bot":false,"login":"cherylstanley","name":"Cheryl Stanley"},"headRefName":"HomePage-Cheryl","number":61,"title":"Home page cheryl","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/61"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-Chatroom-backend-post-get","number":30,"title":"Leon chatroom backend entity and POST/GET APIs","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/30"},{"author":{"id":"MDQ6VXNlcjg2NzQ0NDUx","is_bot":false,"login":"yqin01","name":"Yicheng Qin"},"headRefName":"tim-add-driverToggleButton","number":23,"title":"Tim add driver toggle button","url":"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2/pull/23"}]
